theme: jekyll-theme-tactile
title: Zoe S. Leone
description: I am an urban ecologist, focusing on the impacts of various novel ecosystems on the ecological functionings of mammal and avian populations. I have a MSc in Biology from Chicago State University and the Field Museum of Natural History. I am currently a PhD student at the University of Illinois Chicago studying urban ecology.

